
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/node:13.11.0

    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            EC2_USERNAME=bitnami
            EC2_PUBLIC_DNS=ec2-3-135-235-67.us-east-2.compute.amazonaws.com
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS \
            sudo sh test.sh
